# Generated by Django 5.2.8 on 2025-11-27 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOACAO', 'Doação'), ('EMPRESTIMO', 'Empréstimo'), ('ALUGUEL', 'Aluguel'), ('TROCA', 'Troca')], max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('EM_POSSE', 'Em posse'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('data_limite_devolucao', models.DateField(blank=True, null=True, verbose_name='data limite de devolução')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
                ('livro_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_principais', to='livros.livro', verbose_name='livro principal')),
                ('livros_oferecidos', models.ManyToManyField(blank=True, related_name='transacoes_oferecidas', to='livros.livro', verbose_name='livros oferecidos')),
                ('livros_solicitados', models.ManyToManyField(blank=True, related_name='transacoes_solicitadas_livros', to='livros.livro', verbose_name='livros solicitados')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='HistoricoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('EM_POSSE', 'Em posse'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], max_length=20, verbose_name='status anterior')),
                ('status_novo', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('EM_POSSE', 'Em posse'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], max_length=20, verbose_name='status novo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_transacoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='transacoes.transacao', verbose_name='transação')),
            ],
            options={
                'verbose_name': 'Histórico de transação',
                'verbose_name_plural': 'Históricos de transação',
                'ordering': ('-criado_em',),
            },
        ),
    ]
