# Generated by Django 5.2.8 on 2025-11-27 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='remetente')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='transacoes.transacao', verbose_name='transação')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ('criado_em',),
                'indexes': [models.Index(fields=['transacao', 'criado_em'], name='transacoes__transac_3df73f_idx')],
            },
        ),
    ]
