# Generated by Django 5.2.8 on 2025-11-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email institucional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=50, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos', verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localizacao_bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vinculo_verificado',
            field=models.BooleanField(default=False, verbose_name='vínculo verificado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
