# Generated by Django 5.2.8 on 2025-11-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cidade_usuario_email_institucional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_institucional',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='localizacao_bairro',
        ),
    ]
