# Generated by Django 5.2.8 on 2025-11-26 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDesejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='título desejado')),
                ('autor', models.CharField(blank=True, max_length=255, verbose_name='autor desejado')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN desejado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_desejo', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Item da lista de desejos',
                'verbose_name_plural': 'Lista de desejos',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='ISBN')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('autor', models.CharField(blank=True, max_length=255, verbose_name='autor')),
                ('editora', models.CharField(blank=True, max_length=255, verbose_name='editora')),
                ('ano_publicacao', models.CharField(blank=True, max_length=4, verbose_name='ano de publicação')),
                ('capa_url', models.URLField(blank=True, verbose_name='URL da capa')),
                ('sinopse', models.TextField(blank=True, verbose_name='sinopse')),
                ('modalidades', models.JSONField(default=list, verbose_name='modalidades')),
                ('valor_aluguel_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor semanal do aluguel')),
                ('prazo_emprestimo_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='prazo do empréstimo (dias)')),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponível')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ('-criado_em',),
            },
        ),
    ]
